### ISSUE TITLE
WEBM support?

### ISSUE THREAD

**Issue by princessGasmask** [k1rak1ra/FEMBOY#3]
Not really an issue, but I was curious if WEBM support will be added as the program develops?

**Comment by k1rak1ra** [comment]
Yes it will, I added it to my plan. Since DeepDanbooru only supports static images, there will be some technical details that I will have to work out, but I have a good idea and will implement gif/webm/mp4 support in the coming weeks.

**Comment by princessGasmask** [comment]
Thank you, papa.
